### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#209]
We can prepare roadmap based on sig-etcd questionary, here:

https://docs.google.com/forms/d/e/1FAIpQLSdRBidARjwHZkc3BtdfByP2SZy5jy-mIB0Hvs9GDyB6qhbjLg/viewform

- [ ] Creation of a single node etcd cluster
- [ ] Creation of a 3 or 5 node etcd cluster
- [ ] Creation of a cluster with learners
- [ ] Growing a one node cluster to a 3 node cluster
- [ ] Growing a 3 node cluster to a 5 node cluster
- [ ] Shrinking a 5 node cluster to a 3 node cluster
- [ ] Shrinking a 3 node cluster to a 1 node cluster
- [ ] 1:1 exchange of one node with another node (e.g. to change cloud zones)
- [ ] Creating on-demand backups of a cluster
- [ ] Creating periodic backups of a cluster
- [ ] Creating a new cluster from a backup
- [ ] “Rolling back” a cluster to a backup
- [ ] Recovering a single failed cluster node (still have quorum)
- [ ] Recovering from multiple failed cluster nodes (quorum loss)
- [ ] Moving a cluster node between cloud zones
- [ ] Understanding health of a cluster
- [ ] Understanding performance of a cluster
- [ ] Upgrading a cluster between patch versions
- [ ] Downgrading a cluster between patch versions
- [ ] Upgrading a cluster by one minor version
- [ ] Downgrading a cluster by one minor version
- [ ] Upgrading a cluster by multiple minor versions
- [ ] Downgrading a cluster by multiple minor version
- [ ] Expanding size of backing cloud volumes
- [ ] Shrinking size of backing cloud volumes
- [ ] Moving cloud volumes between types (e.g. HDD -> SSD)
- [ ] Moving cloud volumes between zones
- [ ] Enabling TLS communication
- [ ] Enabling unencrypted communication
